### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by tv104** [rvdkooy/react-resizable-textarea#1]
I'd like to propose some enhancements:
- move handler icon inside the textarea (bottom right), similar to the native chrome/firefox handlers.
- increase minHeight of textarea to 1 "row" (similar to firefox)
![image](https://cloud.githubusercontent.com/assets/1164786/21264405/741e0cfa-c39c-11e6-8699-219618f3d1b1.png)
- transparent background for the handler icon to make it look better on non-white backgrounds:
![image](https://cloud.githubusercontent.com/assets/1164786/21264365/35319656-c39c-11e6-9839-81b073adab39.png)

- auto height sizing according to contents (`row="auto"`?)

**Comment by rvdkooy** [comment]
Nice enhancements!
1. I think this is not possible because chrome positions the scrollbar above the draghandler
2. Good one
3. Good one
4. Good one

Ronald

**Comment by tv104** [comment]
Regarding suggestion 1, I've reached the same conclusion. Most libraries position their handler on top of the scrollbar for all browsers (seems like a usability to me..):
![image](https://cloud.githubusercontent.com/assets/1164786/21344823/03dde910-c69e-11e6-9fa1-51f9a5486f51.png)

What do you think about detecting whether the browser supports resizing through a test like:
````
var txtarea = document.createElement('textarea');
if (txtarea.style.resize !== undefined) {
    console.log('resize supported'); // do nothing
}
````
and only using the resizable-textarea-component if resizing is not supported? We can let the user opt-in to this behavior with a prop `polyfill`:
- `polyfill=true` (default) - resizable-textarea is only applied when resizing is not supported
- `polyfill=false` - resizable-textarea is always applied

**Comment by rvdkooy** [comment]
I'm not sure about the polyfill yet, I also like the idea that the component behaves the same in all browsers

**Comment by tv104** [comment]
I've left auto-height-sizing from my pull as this is quite a big change, and the feature I'm currently working on would not benefit from it. 

In terms of UX, I like GitHub's approach: 
- textareas at the bottom of the page (such as when commenting on an issue) grow according to content, and are not shrinkable to less than their initial height. 
- Inline textareas (such when when code reviewing) stay at a fixed height. 

I may add a feature in the future to auto-fit the contents on mount, but not react to any content updates.
